### ISSUE TITLE
saving CryptoKeyPair

### ISSUE THREAD

**Issue by bblfish** [viagraphs/scalajs-rx-idb#3]
Hi I need to use IndexDB to save a [CryptoKeyPair](http://www.w3.org/TR/WebCryptoAPI/#keypair) which I am in the process of submitting a patch to org.scalajs.dom for. 

Before I spend a lot of time setting everything up, I wanted to make sure I could save a pure JS object using scalajs-rx-idb. Reading your README I can't tell if you only save case classes. This is a particular object because if you make it setting extractable to `false` in the [generateKey method](http://www.w3.org/TR/WebCryptoAPI) as here: 

```scala
GlobalCrypto.crypto.subtle.generateKey(
       RsaHashedKeyGenParams("RSASSA-PKCS1-v1_5",
         2048,
         new BigInteger(js.Array[Short](1, 0, 1)), //65537
         HashAlgorithm.`SHA-256`).asInstanceOf[KeyAlgorithmIdentifier],
      false, // <---- setting extractable to false
      js.Array(KeyUsage.sign)
    )
```

Then I think the private key is not readable.

> While access to the underlying cryptographic key material may be restricted, based upon the extractable attribute, once a key is shared with a destination origin, the source origin can not later restrict or revoke access to the key. 

This blog post ["Saving Cryptographic Keys in the Browser"](http://blog.engelke.com/2014/09/19/saving-cryptographic-keys-in-the-browser/)  explains that one has to save them in IndexDB:

> Because CryptoKey objects are opaque they can’t be placed in localStorage, which only supports simple types. Instead the key store will use IndexedDB, which can clone and store opaque variables. IndexedDB is more complex than localStorage, so dealing with it will be take up much of this post.

If this is possible it might be worth adding that to the README. I know it's a pretty unusual case, but that is why I thought I'd ask.

**Comment by bblfish** [comment]
I asked  [@lihaoi and gitter](https://gitter.im/scala-js/scala-js?at=564742c1aca9bb7c6e50569c) and he
wrote

> Not out of the box but you can teach it. Define an implicit reader and writer for js.Any or something like that and it'll let you read write that type

**Comment by bblfish** [comment]
@lihaoyi's answer on gitter was:

> currently it's written to support both JVM and JS; only the parsing and serializing using the platform stuff IIRC you'd need to make the AST platform dependent to make what you want work
which is plausible e.g. Scalatags' AST is platform dependent at allows for opaque "Javascript Thing" nodes just will take work

**Comment by bblfish** [comment]
Reading through the code here I noticed that perhaps there is not that much to change to get this to work. It seems that one would just need to change [StoreKeyPolicy](https://github.com/viagraphs/scalajs-rx-idb/blob/919d0bc448e2548a3090bcc138d516a683ae1d25/src/main/scala/com/viagraphs/idb/IdbSupport.scala#L177) .

 If that is correct I could look into a better pickling/unpickling library to replace it. Essentially one would need code to transform scala-js objects into clean `js.Object` which for which there can be a [structured clone](https://html.spec.whatwg.org/#structured-clone) as specified by the [IDBObjectStore  put method](http://www.w3.org/TR/IndexedDB/#widl-IDBObjectStore-put-IDBRequest-any-value-any-key). 

I wonder if at a first approximation one can think of it this way: 
1. scala-js to js: any class that extends js.Object can just be passed as is, and any other class needs to be transformed. 
2. js to scala-js: here since we have typed the DB it should be easy to know what objects will come back, one so one just needs a way to map them, either using `.instanceOf[xxx]` or using a constructor.

**Comment by bblfish** [comment]
I have managed [to hack scalajs-rx-idb](https://github.com/bblfish/scalajs-rx-idb/commit/2a8294647713cee209617f0d51af35daa5830b1d) so that it allows me to save the private keys. Essentially it reduces the generality of scalajs-rx-idb, but it would just require a very light weight pickler to get back to full generality.

**Comment by bblfish** [comment]
If something along the lines of https://github.com/lihaoyi/upickle-pprint/pull/122 is enabled then this hack will no longer be needed :-)

**Comment by bblfish** [comment]
It turns out that it is not going to be easy to hack upickle. See https://github.com/lihaoyi/upickle-pprint/issues/127 . This issue is too specific, so I have opened a new issue #5 "enable structured cloning" that covers all the issues of which this is just a particular case.

**Comment by l15k4** [comment]
Hey, sorry that I don't cooperate but the above ^^ is one of the reasons I basically cannot. I haven't used scala.js, Monix, idb, upickle, etc. for more than a year and I completely forgot the stuff ... The overhead would be too high for me right now because I'm involved in way more complicated things...

If you want I can grant you permissions so you can keep pushing it forward if you want, but I can't do that at least for a couple of following months...

**Comment by bblfish** [comment]
It took me a bit of time to understand the problem myself. (and also had a lot of other things to do on the side.)

I think what I may do is just work on my branch to simplify the code as explained in [issue 5: enable structured cloning](https://github.com/viagraphs/scalajs-rx-idb/issues/5) by removing upickle, if it's not too much work. It certainly will be less work than writing my own IndexDB library.
